### ISSUE TITLE
Corner case: Interaction with tombstone by unmodded player leads to item loss.

### ISSUE THREAD

**Issue by Vergeh** [AzumattDev/AzuEPI#2]
I play on a dedicated server where client-side mods are not enforced or synced. Items are usually preserved in tombstones without issue. However, if an unmodded client interacts with a tombstone (in this case, teammate retrieved portal ingredients), the items held in the equipment and quick slots are truncated from the inventory and are subsequently lost, even when the modded owner fetches all items from the tombstone.

**Comment by AzumattDev** [comment]
I'm not sure what you expect me to do here.

**Comment by AzumattDev** [comment]
Closing with no comments after 2 weeks.
